{application,simple_cache,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{sc_app,[]}},
              {env,[]},
              {modules,[sc_app,sc_server,sc_sup,simple_cache_app,
                        simple_cache_sup]}]}.
